const static char http_index_hml[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\">\n"
"    <title>ESP32 WebSocket Test</title>\n"
"	<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\n"
"    <script type=\"text/javascript\">\n"
"	\n"
"		var WebSocket_connection;\n"
"\n"
"		\n"
"	    if (!\"WebSocket\" in window){  \n"
"			alert(\"WebSocket NOT supported by your Browser!\");\n"
"			$('#WebSocket_State').text(\"WebSocket NOT supported by your Browser!\");			\n"
"		}\n"
"		\n"
"		window.onbeforeunload = function() {\n"
"			websocket.onclose = function () {}; // disable onclose handler first\n"
"			websocket.close()\n"
"		};\n"
"				\n"
"		function connect(){\n"
"			WebSocket_connection = new WebSocket($('#websocket_address').val());\n"
"\n"
"			$('#WebSocket_State').text(\"Connecting\");\n"
"			\n"
"			WebSocket_connection.onopen = function(){\n"
"$('#WebSocket_State').html('<input type=\"text\" id=\"websocket_message\" value=\"Data to send\"/><a href=\"javascript:WebSocketSend()\">\
send WebSocket</a>');\n"
"			};\n"
"		   \n"
"			WebSocket_connection.onmessage = function (evt) { \n"
"				//read data and append it to output_div\n"
"				$( \"#output_div\" ).append( evt.data + \"<br>\" );	\n"
"			};\n"
"\n"
"			WebSocket_connection.onerror = function()\n"
"			{\n"
"				$('#WebSocket_State').text(\"Error,...  connection closed\");\n"
"			};\n"
"			\n"
"			WebSocket_connection.onclose = function()\n"
"			{ \n"
"				$('#WebSocket_State').text(\"Disconnected\");\n"
"			};\n"
"		}\n"
"			\n"
"				\n"
"        function WebSocketSend(){\n"
"			WebSocket_connection.send($('#websocket_message').val());\n"
"        }\n"
"		\n"
"      </script>\n"
"		\n"
"   </head>\n"
"   <body>\n"
"\n"
"	<div id=\"WebSocket_State\">\n"
"		WebSocket Server: \n"
"		<input type=\"text\" id=\"websocket_address\" value=\"ws://192.168.4.1:9998\"/>\n"
"		<a href=\"javascript:connect()\">Connect</a>\n"
"		</div>\n"
"	<br>\n"
"	<div id=\"output_div\">\n"
"	Received WebSocket Messages:<br>\n"
"	</div>\n"
"	  \n"
"      \n"
"   </body>\n"
"</html>\n";
