const static char http_index_hml[] =  "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"utf-8\">\n"
"    <title>ESP32 WebSocket Test</title>\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"  	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n"
"  	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"
"  	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n"
"	<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\n"
"	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n"
"\n"
"<style type=\"text/css\">\n"
"body{\n"
"	position: relative;\n"
"}\n"
"#dataBox_div{\n"
"	width: 350px;\n"
"	height: 400px;\n"
"	overflow-y: auto;\n"
"	border: solid 1px;\n"
"	margin-left: 10px;\n"
"	padding-left: 10px;\n"
"	background-color: #1E88E5;\n"
"}\n"
"\n"
"</style>\n"
"\n"
"<script>\n"
"\n"
"//----------------------------------------------------La connection WebSocket-------------------------------------------------\n"
"var WebSocket_connection;\n"
"\n"
"//On vérifie que le browser supporte les websockets\n"
"if (!\"WebSocket\" in window){  \n"
"	alert(\"WebSocket NOT supported by your Browser!\");\n"
"	$('#WebSocket_State').text(\"WebSocket NOT supported by your Browser!\");\n"
"}\n"
"		\n"
"//Avant la fermeture du websocket\n"
"window.onbeforeunload = function() {\n"
"	websocket.onclose = function () {}; // disable onclose handler first\n"
"	websocket.close()\n"
"};\n"
"\n"
"//Fonction qui lance une connection websocket				\n"
"function connect(){\n"
"	//Creation d'une connection websocket à l'adresse indiqué par l'utilisateur\n"
"	WebSocket_connection = new WebSocket($('#websocket_address').val());\n"
"\n"
"	$('#connectionStatus').text(\"Connecting...\");\n"
"	$('#liConnectionButton').attr(\"class\", \"disabled\");\n"
"\n"
"	WebSocket_connection.onopen = function(){\n"
"		$('#liConnectionButton').attr(\"class\", \"\");\n"
"		$('#liConnectionButton').html('<a href=\"javascript:disconnect()\">Disconnect</a>');\n"
"		$('#RecordButton').attr('class', \"\");\n"
"		$('#RecordButton').html('<a href=\"javascript:start()\">Start recording &nbsp <span class=\"glyphicon glyphicon-record\" style=\"color: red;\">\
</span></a>');\n"
"	  	$('#connectionStatus').text(\"Connected\");\n"
"	};\n"
"   \n"
"	WebSocket_connection.onmessage = function (evt) { \n"
"		//read data and append it to output_div\n"
"		var data = evt.data;\n"
"		arr = data.split(\",\");\n"
"		$( \"#dataBox_div\").append( data + \"<br>\" );\n"
"		$( \"#time_value\").text(arr[0]);\n"
"		$('#distance_value').text(arr[1])\n"
"		$( \"#voltage_value\").text(arr[2]);\n"
"		//options_tab[VOLTAGE_OPTIONS].data[selected_data].dataPoints.push({x : arr[0], y : arr[1]});\n"
"		$( \"#speed_value\").text(arr[4]);\n"
"		//options_tab[SPEED_OPTIONS].data[selected_data].dataPoints.push({x : arr[0], y : arr[2]});\n"
"		$( \"#current_value\").text(arr[3]);\n"
"		//options_tab[CURRENT_OPTIONS].data[selected_data].dataPoints.push({x : arr[0], y : arr[3]});\n"
"		//$(\"#chartContainer\").CanvasJSChart().render();\n"
"		//$(\"#chartContainer2\").CanvasJSChart().render();	\n"
"		addToTable(arr);\n"
"		\n"
"		updateData(arr);\n"
"	};\n"
"\n"
"	WebSocket_connection.onerror = function()\n"
"	{\n"
"		$('#connectionStatus').text(\"Error,...  connection closed\");\n"
"	};\n"
"	\n"
"	WebSocket_connection.onclose = function()\n"
"	{ \n"
"		$('#liConnectionButton').attr(\"class\", \"\");\n"
"		$('#liConnectionButton').html('<a href=\"javascript:connect()\">Connect</a>');\n"
"		$('#RecordButton').attr('class', \"disabled\");\n"
"		$('#RecordButton').html('<a href=\"javascript:start()\">Start recording &nbsp <span class=\"glyphicon glyphicon-record\" style=\"color: grey;\">span></a>');\n"
"		$('#connectionStatus').text(\"Disconnected\");\n"
"	};\n"
"}\n"
"\n"
"function disconnect(){\n"
"	WebSocket_connection.close();\n"
"}\n"
"\n"
"function start(){\n"
"	$('#liConnectionButton').attr(\"class\", \"disabled\");\n"
"	$('#RecordButton').html('<a href=\"javascript:stop()\">Stop recording &nbsp <span class=\"glyphicon glyphicon-stop\" style=\"color: red;\"></span>\
</a>');\n"
"	WebSocket_connection.send(\"start\");\n"
"}\n"
"\n"
"function stop(){\n"
"	$('#liConnectionButton').attr(\"class\", \"\");\n"
"	$('#RecordButton').html('<a href=\"javascript:start()\">Start recording &nbsp <span class=\"glyphicon glyphicon-record\" style=\"color: red;\">\
</span></a>');\n"
"	WebSocket_connection.send(\"stop\");\n"
"	updateGraphics();\n"
"}\n"
"\n"
"function WebSocketSend(message){\n"
"	WebSocket_connection.send(message);\n"
"}\n"
"\n"
"\n"
"function addToTable(value){\n"
"	$(\"#table_values\").append(\"<tr><td>\"+value[0]+\"</td><td>\"+value[1]+\"</td><td>\"+value[4]+\"</td><td>\"+value[2]+\"</td><td>\"+value[3]+\"</td>\
tr>\");\n"
"}\n"
"\n"
"function createMenuSave(){\n"
"	\n"
"	$(\"#listeDataToSave\").html(\"\");\n"
"\n"
"	for(var i = 0; i < selected_data + 1; i++){\n"
"		var link = $(\"<a></a>\").attr(\"href\", \"javascript:saveToFile('essai')\");\n"
"		link.text(\"Essai 1\");\n"
"		var list = $(\"<li></li>\").html(link);\n"
"		list.innerHTML = link;\n"
"		$(\"#listeDataToSave\").append(list);\n"
"	}\n"
"}\n"
"\n"
"function saveToFile(filename){\n"
"	$(\"#debug\").text(filename);\n"
"	var text = \"Hello World\";\n"
"	//var file = $(\"#dataBox_div\").val();\n"
"	var dlbtn = document.getElementById(\"saveToFileButton\");\n"
"	var file = new Blob([text], {type: 'text/plain'});\n"
"	dlbtn.href = URL.createObjectURL(file);\n"
"  	dlbtn.download = \"name.txt\";\n"
"}\n"
"\n"
"function newData(){\n"
"	selected_data++;\n"
"	xvalue = 0;\n"
"	for(var i = 0; i < 2; i++){\n"
"		var data_value = new Array();\n"
"		options_tab[i].data.push({type: \"area\", name: \"Essai \" + selected_data + 1, markerSize: 5, showInLegend: true, dataPoints: data_value});\n"
"	}\n"
"}\n"
"//----------------------------------------------------Generation des graphiques------------------------------------------------\n"
"//---------------------------------------------------------\n"
"//********************CONSTANTES***************************\n"
"//---------------------------------------------------------\n"
"var SPEED_OPTIONS 			= 0;\n"
"var CURRENT_OPTIONS 		= 1;\n"
"var VOLTAGE_OPTIONS			= 2;\n"
"\n"
"//---------------------------------------------------------\n"
"//*****************VARIABLES GLOBALES----------------------\n"
"//---------------------------------------------------------\n"
"var options_tab = new Array();\n"
"var selected_data = 0;\n"
"\n"
"//**************************************************************************************************************************************\n"
"function create_options(titre, Xaxis_title, Yaxis_title){\n"
"\n"
"var data_value = new Array();\n"
"\n"
"var op = {\n"
"	animationEnabled: false,\n"
"	theme: \"light2\",\n"
"	title:{\n"
"		text: titre\n"
"	},\n"
"	axisY: {\n"
"		title: Yaxis_title,\n"
"		valueFormatString: \"#0.00\",\n"
"	},\n"
"	axisX:{\n"
"		title: Xaxis_title,\n"
"	},\n"
"	legend: {\n"
"		cursor: \"pointer\",\n"
"		itemclick: function toogleDataSeries(e) {\n"
"						if (typeof (e.dataSeries.visible) === \"undefined\" || e.dataSeries.visible) {\n"
"							e.dataSeries.visible = false;\n"
"						} else {\n"
"							e.dataSeries.visible = true;\n"
"						}\n"
"							e.chart.render();\n"
"						}\n"
"	},\n"
"	toolTip: {\n"
"		shared: true\n"
"    },\n"
"	data: [{\n"
"		type: \"area\",\n"
"		name: \"Essai1\",\n"
"		markerSize: 5,\n"
"		showInLegend: true,\n"
"		//yValueFormatString: \"£#2K\",\n"
"		dataPoints: data_value\n"
"\n"
"	}]\n"
"};\n"
"\n"
"options_tab.push(op);\n"
"\n"
"}\n"
"\n"
"window.onload = function () {\n"
"\n"
"\n"
"\n"
"	create_options(\"Vitesse de la voiture\", \"temps [s]\", \"Vitesse du vehicule [m/s]\");\n"
"	create_options(\"Hello\", \"axe des X\", \"axe des Y\");\n"
"	create_options(\"Hello_2\", \"axe des X\", \"axe des Y\");\n"
"\n"
"	$(\"#chartContainer\").CanvasJSChart(options_tab[SPEED_OPTIONS]);\n"
"	$(\"#chartContainer2\").CanvasJSChart(options_tab[CURRENT_OPTIONS]);\n"
"	$(\"#chartContainer3\").CanvasJSChart(options_tab[VOLTAGE_OPTIONS]);\n"
"	//updateData();\n"
"}\n"
"\n"
"function updateData(value){\n"
"	options_tab[SPEED_OPTIONS].data[selected_data].dataPoints.push({x : parseFloat(value[0]), y : parseInt(value[4])});\n"
"	options_tab[CURRENT_OPTIONS].data[selected_data].dataPoints.push({x : parseFloat(value[0]), y : parseInt(value[3])});\n"
"	options_tab[VOLTAGE_OPTIONS].data[selected_data].dataPoints.push({x : parseFloat(value[0]), y : parseInt(value[2])});	\n"
"}\n"
"\n"
"var xvalue = 0;\n"
"var yvalue = 0;\n"
"var yvalue2 = 0;\n"
"var yvalue3 = 0;\n"
"\n"
"function updateGraphics(){\n"
"	\n"
"	$(\"#chartContainer\").CanvasJSChart().render();\n"
"	$(\"#chartContainer2\").CanvasJSChart().render();\n"
"	$(\"#chartContainer3\").CanvasJSChart().render();\n"
"}\n"
"\n"
"function addData(value){\n"
"\n"
"	options_tab[SPEED_OPTIONS].data[selected_data].dataPoints.push({x : xvalue, y : yvalue});\n"
"	options_tab[CURRENT_OPTIONS].data[selected_data].dataPoints.push({x : xvalue, y : yvalue});\n"
"	xvalue++;\n"
"	$(\"#chartContainer\").CanvasJSChart().render();\n"
"	$(\"#chartContainer2\").CanvasJSChart().render();\n"
"	var value = new Array();\n"
"	value[0] = xvalue;\n"
"	value[1] = yvalue;\n"
"	value[2] = yvalue2\n"
"	value[3] = yvalue3;\n"
"	addToTable(value);\n"
"	setTimeout(updateData, 50);\n"
"}\n"
"/*\n"
"function updateData(){\n"
"    yvalue = Math.floor((Math.random() * 100) + 1);\n"
"    yvalue2 = Math.floor((Math.random() * 100) + 1);\n"
"    yvalue3 = Math.floor((Math.random() * 100) + 1);\n"
"   \n"
"    addData();\n"
"}\n"
"*/\n"
"</script>\n"
"\n"
"\n"
"</head>\n"
"\n"
"<body data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\n"
"\n"
"<div class=\"jumbotron\" style=\"padding-top: 50px;\">\n"
"	<!-- NAVIGATION BAR -->\n"
"	<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n"
"		<div class=\"container-fluid\">\n"
"			<div class=\"navbar-header\">\n"
"				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
"        		<span class=\"icon-bar\"></span>\n"
"        		<span class=\"icon-bar\"></span>\n"
"        		<span class=\"icon-bar\"></span>                        \n"
"      			</button>\n"
"				<a class=\"navbar-brand\" href=\"#\">Data Center</a>\n"
"			</div>\n"
"			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
"				<ul class=\"nav navbar-nav\">\n"
"					<li><a data-toggle=\"modal\" href=\"#parameterModal\">Parameters</a></li>\n"
"					<li id=\"liConnectionButton\"><a id=\"connectButton\" href=\"javascript:connect()\">Connect</a></li>\n"
"					<li id=\"RecordButton\" class=\"disabled\"><a href=\"javascript:start()\">Start recording &nbsp <span class=\"glyphicon glyphicon-record\" style=\"color: grey;\"></span></a></li>\n"
"					<li><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Outils <span class=\"glyphicon glyphicon-chevron-down\"></span> </a>\n"
"						<ul class=\"dropdown-menu\">\n"
"							<li><a href=\"#\">Envoyer par courriel</a></li>\n"
"							<li><a href=\"javascript:saveToFile()\">Save to file</a></li>\n"
"							<li><a data-toggle=\"modal\" href=\"#saveDataSelector\">Save to file _ modal</a></li>\n"
"	          				<li><a href=\"javascript:newData()\">Nouvelle série</a></li>\n"
"	          				<li><a href=\"#\">À propos</a></li>\n"
"						</ul>\n"
"					</li>\n"
"				</ul>\n"
"			</div>				\n"
"		</div>\n"
"\n"
"	</nav>\n"
"\n"
"	<div class=\"well\" style=\"padding-top: 0px; padding-bottom: 0px; margin-bottom: 0px;\">\n"
"		<h4>Connection status : <span id=\"connectionStatus\">Disconnected</span></h4>\n"
"	</div>\n"
"\n"
"\n"
"	<div class=\"panel-group\">\n"
"  		<div class=\"panel panel-default\">\n"
"    		<div class=\"panel-heading\">\n"
"      			<h4 class=\"panel-title\">\n"
"        		<a data-toggle=\"collapse\" href=\"#liveData\">Données en direct</a>\n"
"      			</h4>\n"
"    		</div>\n"
"    		<div id=\"liveData\" class=\"panel-collapse collapse\">\n"
"      			<div class=\"panel-body\">\n"
"      				<div class=\"row\">\n"
"      					<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"      						<h4>Temps <span id=\"time_value\">0.00</span> s.</h4>\n"
"      					</div>\n"
"      					<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"      						<h4>Tension <span id=\"voltage_value\">0.00</span> mV.</h4>\n"
"      					</div>\n"
"      					<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"      						<h4>Courant <span id=\"current_value\">0.00</span> mA.</h4>\n"
"      					</div>\n"
"      					<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"      						<h4>Vitesse <span id=\"speed_value\">0.00</span> m/s.</h4>\n"
"      					</div>\n"
"      					<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"      						<h4>Distance <span id=\"distance_value\">0.00</span> mm.</h4>\n"
"      					</div>\n"
"      				</div>\n"
"      			<!--<div class=\"panel-footer\">Panel Footer</div>-->\n"
"    			</div>\n"
"  			</div>\n"
"		</div> \n"
"	</div>\n"
"\n"
"	<ul class=\"nav nav-tabs\">\n"
"		<li class=\"active\"><a data-toggle=\"tab\" href=\"#table\">Données</a></li>\n"
"  		<li><a data-toggle=\"tab\" href=\"#graph\">Graphiques</a></li>\n"
"  		<li><a data-toggle=\"tab\" href=\"#menu2\">Tableau</a></li>\n"
"  		<li><a data-toggle=\"tab\" href=\"#real_tab\">Tableau_real</a></li>\n"
"	</ul>\n"
"\n"
"	<div class=\"tab-content\">\n"
"  		<div id=\"table\" class=\"tab-pane fade in active\">\n"
"    		<h3>HOME</h3>\n"
"			<div class=\"row\">\n"
"				<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"					<h4>Temps <span id=\"time_live\">0.00</span> s.</h4>\n"
"				</div>\n"
"				<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"					<h4>Tension <span id=\"time_live\">0.00</span> mV.</h4>\n"
"				</div>\n"
"				<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"					<h4>Courant <span id=\"time_live\">0.00</span> mA.</h4>\n"
"				</div>\n"
"				<div class=\"col-lg-2 col-md-6 col-sm-6 col-xs-12\">\n"
"					<h4>Vitesse <span id=\"time_live\">0.00</span> m/s.</h4>\n"
"				</div>\n"
"			</div>\n"
"  		</div>\n"
"  		<div id=\"graph\" class=\"tab-pane fade\">\n"
"    		<h3>Graphique</h3>\n"
"			<div id=\"chartContainer\" style=\"height: 300px; width: 100%; margin-bottom: 20px;\"></div>\n"
"			<div id=\"chartContainer2\" style=\"height: 300px; width: 100%;margin-bottom: 20px;\"></div>\n"
"			<div id=\"chartContainer3\" style=\"height: 300px; width: 100%;margin-bottom: 20px;\"></div>\n"
"  		</div>\n"
"  		<div id=\"menu2\" class=\"tab-pane fade\">\n"
"    		<h3>Menu 2</h3>\n"
"    			<div id=\"dataBox_div\" class=\"container-fluid\">\n"
"					time (s), Tension (mV), Vitesse (m/s)<br>\n"
"				</div>\n"
"  		</div>\n"
"  		<div id=\"real_tab\" class=\"tab-pane fade\" style=\"height: 400px; overflow-y: auto;\">\n"
"  			<h3>Tableaux de données</h3>\n"
"  			<div class=\"col-lg-3 col-xs-12\">\n"
"  			<table class=\"table\" >\n"
"				<thead>\n"
"					<tr>\n"
"						<td>Time [s]</td>\n"
"						<td>Distance [mm]</td>\n"
"						<td>Speed [m/s]</td>\n"
"						<td>Current [A]</td>\n"
"						<td>Voltage [mV]</td>\n"
"					</tr>\n"
"				</thead>\n"
"				<tbody id=\"table_values\">\n"
"					\n"
"				</tbody>\n"
"  			</table>\n"
"  			</div>\n"
"  		</div>\n"
"	</div>\n"
"\n"
"	<div id=\"debug\"></div>\n"
"\n"
"<!-- Modal PARAMETERS WINDOW-->\n"
"<div class=\"modal fade\" id=\"parameterModal\" role=\"dialog\">\n"
"    <div class=\"modal-dialog\">\n"
"    \n"
"      	<!-- Modal content-->\n"
"      	<div class=\"modal-content\">\n"
"        	<!-- CONFIG MENU HEADER -->\n"
"        	<div class=\"modal-header\">\n"
"          		<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
"          		<h4 class=\"modal-title\">Paramaters</h4>\n"
"        	</div>\n"
"        	<!-- CONFIG MENU BODY -->\n"
"        	<div class=\"modal-body\">\n"
"          		<p>IP address of the module\n"
"          		<input type=\"text\" id=\"websocket_address\" value=\"ws://192.168.4.1:9998\"/></p>\n"
"          		<p>Data sampling frequency\n"
"          		<input type=\"text\" id=\"frequencyValue\" value=\"20\"/>Hz</p>\n"
"          		<p>Test duration\n"
"          		<input type=\"text\" id=\"testDurationValue\" value=\"10\"/>second</p>\n"
"        	</div>\n"
"        	<!-- CONFIG MENU FOOTER -->\n"
"        	<div class=\"modal-footer\">\n"
"        		<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Save</button>\n"
"          		<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"
"        	</div>\n"
"      	</div>\n"
"      \n"
"    </div>\n"
"</div>\n"
"<!-- END of Modal -->\n"
"\n"
"<div class=\"modal fade\" id=\"saveDataSelector\" role=\"dialog\">\n"
"	<div class=\"modal-dialog\">\n"
"		<div class=\"modal-content\">\n"
"			<div class=\"modal-header\">\n"
"          		<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n"
"          		<h4 class=\"modal-title\">Select data to save</h4>				\n"
"			</div>\n"
"			<div class=\"modal-body\">\n"
"				<div class=\"dropdown\">\n"
"					<button class=\"btn btn-default dropdown-toggle\" type=\"button\" onclick=\"javascript:createMenuSave()\" data-toggle=\"dropdown\"><span class=\"caret\"></span></button>\n"
"					<ul class=\"dropdown-menu\" id=\"listeDataToSave\">\n"
"						\n"
"					</ul>\n"
"				</div>\n"
"			</div>\n"
"			<div class=\"modal-footer\">\n"
"				<a href=\"javascript:void(0)\" id=\"saveToFileButton\"><button type=\"button\" class=\"btn btn-default\">Save</button></a>\n"
"				<a href=\"#\"><button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button></a>\n"
"			</div>\n"
"		</div>\n"
"		\n"
"	</div>\n"
"</div>\n"
"\n"
"<script src=\"https://canvasjs.com/assets/script/jquery-1.11.1.min.js\"></script>\n"
"<script src=\"https://canvasjs.com/assets/script/jquery.canvasjs.min.js\"></script>\n"
"\n"
"\n"
"\n"
"</div>		\n"
"\n"
"</body>\n"
"</html>;\n";